# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

nodejs_version: 0.10

install:
  - npm install -g purplecabbage/cordova-paramedic

build: off

test_script:
  - node --version
  - npm --version
  - msbuild /version

  - cordova-paramedic --plugin C:\projects\cordova-plugin-device --platform windows  
